language: ruby
rvm:
  - 1.8.7
gemfile:
  - crowbar_framework/Gemfile
bundler_args: --without development
script: 'cd crowbar_framework && bundle exec rake db:drop railties:install:migrations db:migrate db:fixtures:dump test:units spec'
