language: ruby
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: 2.0.0
gemfile:
  - crowbar_framework/Gemfile
bundler_args: --without development
script: 'cd crowbar_framework && bundle exec rake db:drop railties:install:migrations db:migrate db:fixtures:dump test:units spec'
notifications:
  email:
    - crowbar@dell.com
  irc:
    on_success: change
    on_failure: always
    channels:
      - irc.freenode.org#crowbar
